# Generated by Django 4.1 on 2023-11-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_voting_postproc_alter_voting_tally'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='private',
            field=models.BooleanField(default=False, help_text='If it is checked, the voting will be anonymous'),
        ),
    ]
